logLevel: debug
host: "0.0.0.0"
port: 8080

healthCheckTimeout: 400
globalTTL: 1800

matrix:
  vars:
    generic: "lovedheart/Qwen3.5-9B-FP8"
    coder: "Qwen/Qwen3.6-35B-A3B-FP8"
    nomic: "nomic-ai/nomic-embed-text-v1.5"

  evict_costs:
    generic: 10
    m: 30
    nomic: 1

  sets:
    coder_suite: "generic & coder & nomic"

hooks:
  on_startup:
    preload: ["nomic-ai/nomic-embed-text-v1.5", "lovedheart/Qwen3.5-9B-FP8", "Qwen/Qwen3.6-35B-A3B-FP8"]

models:
  "lovedheart/Qwen3.5-9B-FP8":
    checkEndpoint: /v1/models
    cmd: >
      docker run --rm --runtime=nvidia
      --gpus '"device=${env.LLM_DEVICE_ID_0}"'
      --network llm-network
      --name vllm-${PORT}
      -v ${env.HF_HOME}:/root/.cache/huggingface
      vllm/vllm-openai:latest
        --model lovedheart/Qwen3.5-9B-FP8
        --port ${PORT}
        --host 0.0.0.0
        --gpu-memory-utilization 0.95
        --enable-prefix-caching
        --max-model-len 248320
        --kv-cache-dtype auto
        --attention-backend flashinfer
        --mamba-cache-mode align
        --mamba-block-size 8

    cmdStop: "docker stop vllm-${PORT} || true"
    proxy: http://vllm-${PORT}:${PORT}
    type: proxy

  "Qwen/Qwen3.6-35B-A3B-FP8":
    checkEndpoint: /v1/models
    cmd: >
      docker run --rm --runtime=nvidia
      --gpus '"device=${env.LLM_DEVICE_ID_1},${env.LLM_DEVICE_ID_2}"'
      --network llm-network
      --name vllm-${PORT}
      -v ${env.HF_HOME}:/root/.cache/huggingface
      vllm/vllm-openai:latest
      --model Qwen/Qwen3.6-35B-A3B-FP8
      --host 0.0.0.0
      --port ${PORT}
      --tensor-parallel-size 2
      --enable-chunked-prefill
      --max-model-len 262144
      --gpu-memory-utilization 0.93
      --reasoning-parser qwen3
      --enable-auto-tool-choice
      --tool-call-parser qwen3_coder
      --speculative-config '{"method":"qwen3_next_mtp","num_speculative_tokens":1}'
      --enable-prefix-caching
      --cpu-offload-gb 6
      --max-num-seqs 1
      --kv-cache-dtype fp8_e4m3
      --max-num-batched-tokens 131072
      --disable-custom-all-reduce
    cmdStop: "docker stop vllm-${PORT} || true"
    proxy: http://vllm-${PORT}:${PORT}
    type: proxy

  "nomic-ai/nomic-embed-text-v1.5":
    checkEndpoint: /v1/models
    cmd: >
      docker run --rm --runtime=nvidia
      --gpus "device=${env.INDEXER_STORAGE_DEVICE_ID}"
      --network llm-network
      --name vllm-${PORT}
      -v ${env.HF_HOME}:/root/.cache/huggingface
      vllm/vllm-openai:latest
      --model nomic-ai/nomic-embed-text-v1.5
      --host 0.0.0.0
      --port ${PORT}
      --max-model-len 2048
      --gpu-memory-utilization 0.25
      --trust-remote-code
    cmdStop: "docker stop vllm-${PORT} || true"
    proxy: http://vllm-${PORT}:${PORT}
    type: proxy
