services:
  coder_qdrant:
    image: qdrant/qdrant:latest
    container_name: coder_qdrant-service
    restart: unless-stopped
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC API (Optional but recommended)
    profiles: [ "coder" ]
    volumes:
      - ${DATA_DIR}/qdrant_storage:/qdrant/storage

  llama-swap:
    image: ghcr.io/mostlygeek/llama-swap:unified-cuda
    container_name: llama-swap-service
    ports:
      - "${LLM_PORT}:8080"
    volumes:
      - ${HF_HOME}:/root/.cache/huggingface
      - ./config.yaml:/app/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
    profiles: [ "coder" ]
    environment:
      - HF_HOME=${HF_HOME}
      - HF_TOKEN=${HF_TOKEN}
      - LLM_DEVICE_ID_1=${LLM_DEVICE_ID_1}
      - LLM_DEVICE_ID_2=${LLM_DEVICE_ID_2}
      - INDEXER_STORAGE_DEVICE_ID=${INDEXER_STORAGE_DEVICE_ID}
    networks:
      - llm-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: --config /app/config.yaml --listen 0.0.0.0:8080

networks:
  llm-network:
    name: llm-network